module.exports = {
  careers: [
    'intro',
    'scoring',
    {
      type: 'category',
      label: 'Engineer (ENG)',
      items: [
        {
          type: 'autogenerated', dirName: 'eng'
        }
      ]
    },
    {
      type: 'category',
      label: 'Engineering Manager (EM)',
      items: [
        {
          type: 'autogenerated', dirName: 'em'
        }
      ]
    }
  ]
}